# Generated by Django 4.2.4 on 2023-08-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_num', models.AutoField(db_index=True, default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=80)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('iso', models.CharField(max_length=3)),
            ],
        ),
    ]
